# Generated by Django 5.2.7 on 2025-10-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(blank=True, choices=[('Electronics', 'ELECTRONICS'), ('Beauty', 'BEAUTY'), ('Sports', 'SPORTS'), ('Books', 'BOOKS'), ('Toys', 'TOYS'), ('Furniture', 'FURNITURE'), ('Appliances', 'APPLIANCES'), ('Footwear', 'FOOTWEAR'), ('Accessories', 'ACCESSORIES'), ('Kitchen', 'KITCHEN'), ('Watches', 'WATCHES'), ('Jewellery', 'JEWELLERY'), ('Stationery', 'STATIONERY'), ('Groceries', 'GROCERIES'), ('Clothing', 'CLOTHING')], max_length=70, null=True)),
            ],
        ),
    ]
