# Generated by Django 5.2.7 on 2025-10-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Electronics', 'ELECTRONICS'), ('Beauty', 'BEAUTY'), ('Sports', 'SPORTS'), ('Books', 'BOOKS'), ('Toys', 'TOYS'), ('Furniture', 'FURNITURE'), ('Appliances', 'APPLIANCES'), ('Footwear', 'FOOTWEAR'), ('Accessories', 'ACCESSORIES'), ('Kitchen', 'KITCHEN'), ('Watches', 'WATCHES'), ('Jewellery', 'JEWELLERY'), ('Stationery', 'STATIONERY'), ('Groceries', 'GROCERIES'), ('Clothing', 'CLOTHING')], max_length=70, null=True),
        ),
    ]
