"""
Django settings for cartnova project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-yfj7ihudhm#$x6%lln*$uo7xc*h6c2r*t$2!wo7xrxc+b@=^#s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False # Kept as False per user request

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'shop_app',
    'rest_framework',
    'corsheaders', # for handling CORS

    'django.contrib.sites', # Required by allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # --- Only Google provider ---
    'allauth.socialaccount.providers.google',
    # 'allauth.socialaccount.providers.microsoft', # REMOVED
    'rest_framework_simplejwt',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware', # CORS headers must be placed high up
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware', # Add allauth middleware AFTER AuthenticationMiddleware
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Add your React frontend development server URL here
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
]

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # React development server (example)
    "http://localhost:5174",  # Vue development server (example)
    "http://localhost:5175",  # Alternative localhost format (example)
]
CORS_ALLOW_ALL_ORIGINS = True # Kept as True per user request

ROOT_URLCONF = 'cartnova.urls'

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# --- CORRECTED Allauth Account Settings ---
ACCOUNT_EMAIL_VERIFICATION = 'none'   # Keep as 'none' for now
ACCOUNT_ADAPTER = 'core.adapters.CustomAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'core.adapters.CustomSocialAccountAdapter'


ACCOUNT_LOGIN_METHODS = {'email'} 
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_USER_MODEL_USERNAME_FIELD = 'username'


# Redirect URLs
LOGIN_REDIRECT_URL = '/'
# ACCOUNT_LOGOUT_REDIRECT_URL = '/' # Optional: uncomment if needed

# --- Provider Specific Settings (Only Google) ---
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'VERIFIED_EMAIL': True,
    },
}

ACCOUNT_ADAPTER = 'core.adapters.CustomAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'core.adapters.CustomSocialAccountAdapter'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cartnova.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'cartnova_db',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}

# Password validation and Internationalization remain the same
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True

# Static files and Media File Configuration
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'core.CustomerUser' # Correct

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

# --- Payment Gateway Settings ---
RAZORPAY_KEY_ID = "rzp_test_RYxqcoMp46Y3yc"
RAZORPAY_KEY_SECRET = "00TFJQzdxdIlYP6EjbmxwMo5"
PAYPAL_CLIENT_ID = "AVj6zN6mWe-5begZfoXssJKTmZfupJ1LWU346-BX5sryyyVrpmP64xYYJBE6f55uYQkB-1xaf45IYFFx"
PAYPAL_CLIENT_SECRET = "EC0zftmhmxyd_XoAAxsnhabrn56caIyUOce5K7i-6jyJErvdJTT6obtqIRm9cX2P9HPLTok5O8fvrtee"
PAYPAL_API_BASE_URL = "https://api-m.sandbox.paypal.com" # Use the API URL

# --- reCAPTCHA Keys ---
GOOGLE_RECAPTCHA_SITE_KEY = '6LdRFfkrAAAAAMGgrtj7nlPy_ZFri__G0dCKbXWZ'
GOOGLE_RECAPTCHA_SECRET_KEY = '6LdRFfkrAAAAAGIBfe3arHdmMBzkrS2wl2xTZeFX'